name: Verify GitHub Secrets

on:
  push:
    branches: [main]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret output
        run: echo "TEST_SECRET = ${{ secrets.TEST_SECRET }}"

